openapi: "3.0.3"
info:
  title: Shac API
  contact:
    email: kayvieider97@gmail.com
  version: 0.0.1
paths:
  /accounts:
    get:
      operationId: GetAccounts
      description: Returns all Accounts
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      $ref: "#/components/schemas/Account"
    post:
      operationId: CreateAccount
      description: Insert a new Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountPostBody"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "400":
          description: Invalid request body. The message will vary depending on the cause.

  /accounts/{accountId}:
    get:
      operationId: GetAccounts
      description: Returns single Account by id
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "404":
          description: Returns an error if the provided account ID was not found.

    patch:
      operationId: UpdateAccount
      description: Update a Account
      parameters:
        - $ref: "#/components/parameters/AccountId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountPatchBody"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "400":
          description: Invalid request body. The message will vary depending on the cause.

    delete:
      operationId: DeleteAccount
      description: Remove a Account
      parameters:
        - $ref: "#/components/parameters/AccountId"
      responses:
        "204":
          description: Successful operation
        "404":
          description: User not found

  /creators/{creatorId}/accounts:
    get:
      operationId: GetCreatorAccounts
      description: Returns all Accounts by creator id
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      $ref: "#/components/schemas/Account"

  /creators/{creatorId}/accounts/votes:
    get:
      operationId: GetCreatorAccountVote
      description: Returns all accounts where creator voted
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      $ref: "#/components/schemas/Account"

  /creators/{creatorId}//accounts/{accountId}/votes:
    get:
      operationId: GetCreatorAccountVote
      description: Return votes of Account
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  vote:
                    $ref: "#/components/schemas/Vote"
        "404":
          description: Returns an error if the provided account ID was not found.

  /platforms:
    get:
      operationId: GetPlatforms
      description: Return all platforms
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  platforms:
                    type: array
                    items:
                      $ref: "#/components/schemas/Platform"

  /votes:
    post:
      operationId: CreateVote
      description: Insert a new vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoteBody"
      responses:
        "200":
          description: Get vote
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vote"
        "400":
          description: Invalid request body. The message will vary depending on the cause.

  /votes/{voteId}:
    delete:
      operationId: DeleteVote
      description: Remove a vote
      parameters:
        - $ref: "#/components/parameters/VoteId"
      responses:
        "204":
          description: Successful operation
        "404":
          description: Vote not found

components:
  parameters:
    AccountId:
      name: account_id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    VoteId:
      name: vote_id
      in: path
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        username:
          type: string
          example: jondoe
        password:
          type: string
          example: password
        created_at:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        creator_id:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        votes_up:
          type: integer
          example: 10
        votes_down:
          type: integer
          example: 5
        platform_id:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        platform_name:
          type: string
          example: instagram
        platform_url:
          type: string
          example: http://www.instagram.com
    AccountPatchBody:
      type: object
      required:
        - username
        - password
        - platform_id
      properties:
        username:
          type: string
          example: jondoe
        password:
          type: string
          example: password
        platform_id:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
    AccountPostBody:
      type: object
      required:
        - username
        - password
        - platform_id
        - creator_id
      allOf:
        - $ref: "#/components/schemas/AccountPatchBody"
        - type: object
          properties:
            creator_id:
              type: string
              format: uuid
              example: e0476273-83cd-4772-a4f9-f0280e3bb2af
    Vote:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        value:
          type: string
          example: up
        creator_id:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        account_id:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        username:
          type: string
          example: jondoe
        platform_name:
          type: string
          example: Facebook
    VoteBody:
      type: object
      required:
        - value
        - accountId
        - creatorId
      properties:
        value:
          type: string
          example: up
        accountId:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        creatorId:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
    Platform:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        name:
          type: string
          example: instagram
        url:
          type: string
          example: http://www.instagram.com
