openapi: "3.0.3"
info:
  title: Shac API
  contact:
    email: on3k.dev@gmail.com
  version: 0.0.1
paths:
  /accounta:
    get:
      operationId: GetAccounts
      description: Returns all Accounts
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                        username:
                          type: string
                          example: jondoe
                        passord:
                          type: string
                          example: password123
                        votesUp:
                          type: integer
                          example: 10
                        votesDown:
                          type: integer
                          example: 5
                        platformId:
                          type: string
                          format: uuid
                          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                        name:
                          type: string
                          example: instagram
                        url:
                          type: string
                          example: http://www.instagram.com

    post:
      operationId: CreateAccount
      description: Insert a new Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - platformId
                - creatorId
              properties:
                username:
                  type: string
                  example: jondoe
                password:
                  type: string
                  example: password
                platformId:
                  type: string
                  format: uuid
                  example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                creatorId:
                  type: string
                  format: uuid
                  example: e0476273-83cd-4772-a4f9-f0280e3bb2af
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                  username:
                    type: string
                    example: jondoe
                  passord:
                    type: string
                    example: password
                  platformId:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                  creatorId:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        "400":
          description: Invalid request body. The message will vary depending on the cause.

  /account/{accountId}:
    get:
      operationId: GetAccounts
      description: Returns single Account by id
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                  username:
                    type: string
                    example: jondoe
                  passord:
                    type: string
                    example: password
                  platformId:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                  creatorId:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        "404":
          description: Returns an error if the provided account ID was not found.

    patch:
      operationId: UpdateAccount
      description: Update a Account
      parameters:
        - $ref: "#/components/parameters/accountId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - platformId
              properties:
                username:
                  type: string
                  example: jondoe
                password:
                  type: string
                  example: password
                platformId:
                  type: string
                  format: uuid
                  example: e0476273-83cd-4772-a4f9-f0280e3bb2af
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                  username:
                    type: string
                    example: jondoe
                  passord:
                    type: string
                    example: password
                  platformId:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                  creatorId:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        "400":
          description: Invalid request body. The message will vary depending on the cause.

    delete:
      operationId: DeleteAccount
      description: Remove a Account
      parameters:
        - $ref: "#/components/parameters/accountId"
        - in: path
          name: accountId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Successful operation
        "404":
          description: User not found

  /accounts/{accountId}/votes:
    get:
      operationId: GetAccountVotes
      description: Return votes of Accounts
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  accounts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                        value:
                          type: string
                          example: up
                        accountId:
                          type: string
                          format: uuid
                          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                        creatorId:
                          type: string
                          format: uuid
                          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        "404":
          description: Returns an error if the provided account ID was not found.

  /creators/{creatorId}/accounts:
    get:
      operationId: GetCreatorsAccounts
      description: Returns all Accounts by creator id
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                        username:
                          type: string
                          example: jondoe
                        passord:
                          type: string
                          example: password123
                        votesUp:
                          type: integer
                          example: 10
                        votesDown:
                          type: integer
                          example: 5
                        platformId:
                          type: string
                          format: uuid
                          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                        name:
                          type: string
                          example: instagram
                        url:
                          type: string
                          example: http://www.instagram.com

  /creators/{creatorId}/votes:
    get:
      operationId: GetCreatorsVotes
      description: Returns all votes by creator id
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                        username:
                          type: string
                          example: jondoe
                        passord:
                          type: string
                          example: password123
                        PlatformName:
                          type: string
                          example: instagram

  /platforms:
    get:
      operationId: GetPlatforms
      description: Return all platforms
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  accounts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                        name:
                          type: string
                          example: Instagram
                        url:
                          type: string
                          example: https://www.instagram.com

  /votes:
    post:
      operationId: CreateVote
      description: Insert a new vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - value
                - accountId
                - creatorId
              properties:
                value:
                  type: string
                  example: up
                accountId:
                  type: string
                  format: uuid
                  example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                creatorId:
                  type: string
                  format: uuid
                  example: e0476273-83cd-4772-a4f9-f0280e3bb2af
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                  value:
                    type: string
                    example: up
                  accountId:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
                  creatorId:
                    type: string
                    format: uuid
                    example: e0476273-83cd-4772-a4f9-f0280e3bb2af
        "400":
          description: Invalid request body. The message will vary depending on the cause.

  /votes/{voteId}:
    delete:
      operationId: DeleteVote
      description: Remove a vote
      parameters:
        - $ref: "#/components/parameters/voteId"
        - in: path
          name: voteId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Successful operation
        "404":
          description: Vote not found

components:
  parameters:
    accountId:
      name: accountId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    voteId:
      name: voteId
      in: path
      required: true
      schema:
        type: string
        format: uuid
